# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopGithubRepos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopGithubRepos
  pod 'SwiftGen'

  target 'PopGithubReposTests' do
    inherit! :search_paths
    pod 'Sourcery'
    pod 'Nimble'
  end

end

target 'PopGithubReposBusinessLogic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopGithubReposBusinessLogic

  target 'PopGithubReposBusinessLogicTests' do
    inherit! :search_paths
    pod 'Sourcery'
    pod 'Nimble'
  end

end
